name: geocoding_resolver
description: Package to translate geographic coordinates into an address and vice versa.
version: 0.0.3+2
homepage: https://github.com/ahmedsaleh210/geocoding_resolver.git
repository: https://github.com/ahmedsaleh210/geocoding_resolver.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
